[[redirects]]
  from = "/api/*"
  to   = "http://68.168.216.251:8055/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/items/*"
  to     = "http://68.168.216.251:8055/items/:splat"
  status = 200
  force  = true
  
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
